### ISSUE TITLE
Command-line selection of basis function is not working

### ISSUE THREAD

**Issue by hkayabilisim** [app2scale/hdmr-opt#10]
## What is the problem?
When I try to use **basisFunction** command-line parameter, the program gives an error message and stops.

## How to repeat
By using the commit version [f3dc28d](https://github.com/app2scale/hdmr-opt/commit/f3dc28dd7c68ec1bea93546542d3b99ec89baa0f), issue the following command:
~~~bash
$ python3 src/main.py --numSamples 1000 --numVariables 2 --function ackley_2d \ 
    --min -30 --max 30 --randomInit --basisFunction Cosine
usage: HDMR [-h] --numSamples NUMSAMPLES --numVariables NUMVARIABLES --function FUNCTION --min MIN --max MAX [--randomInit] [--basisFunction BASISFUNCTION]
            [--legendreDegree LEGENDREDEGREE] [--adaptive] [--numClosestPoints NUMCLOSESTPOINTS] [--epsilon EPSILON] [--clip CLIP]
HDMR: error: argument --basisFunction: invalid int value: 'Cosine'
~~~
It's screenshot is below.
<img width="1111" alt="image" src="https://github.com/app2scale/hdmr-opt/assets/2515171/c3e52a2d-8607-4431-8845-1be3fef3779c">

**Comment by YunusKaratepe** [comment]
This bug is fixed with the last update. There were problem on the function parameter ordering. Now should be working good on both command line and the UI.
