### ISSUE TITLE
Calculating average relative error

### ISSUE THREAD

**Issue by hkayabilisim** [app2scale/hdmr-opt#11]
For each benchmark case, fix parameters and do 100 random tests with different random initializations. Average error will be reported.

This feature could be added to command-line version. 

* metric --> to be decided
* relativity --> according to range

**Comment by YunusKaratepe** [comment]
This feature is added with the commit e25d5ea25df946e4d19f7c9c5e60e340c4e9a198. Euclidean distance is used as error metric.

**Comment by YunusKaratepe** [comment]
This feature is added with the commit e25d5ea25df946e4d19f7c9c5e60e340c4e9a198. Euclidean distance is used as error metric.
