### ISSUE TITLE
Obtain working parameters for benchmark problems

### ISSUE THREAD

**Issue by hkayabilisim** [app2scale/hdmr-opt#6]
Using trial-and-error, it would be nice to find a working set of parameters for all benchmark functions.

rastgrin: -m 3 sample_size 1000, ... --> HDMR finds the optima.
....

**Comment by erdemyelken** [comment]
Upon analyzing the performed operations and the obtained results, it is evident that the adaptive HDMR optimization successfully identified the optimal point and exhibited a short processing time. Furthermore, it was observed that the cosine basis set outperformed the Legendre basis set, particularly in certain benchmark functions.

The achieved results have been documented in the HDMR-OPT Results Summary table.
