### ISSUE TITLE
Implement Cosine basis

### ISSUE THREAD

**Issue by hkayabilisim** [app2scale/hdmr-opt#9]
In addition to the default Legendre basis, it would be nice to select Cosine basis for calculations. The orthonormal cosine basis is defined as follows:

$$
\varphi_k(x) = \sqrt{\frac{1}{b_k-a_k} \frac{8\pi k}{\sin 4\pi k + 4\pi k}}\cos(2\pi k \frac{x - a_k}{b_k-a_k})
$$

The user will now have two options for orthonormal basis: "Legendre" and "Cosine".

The validation of the new cosine basis is [here](https://app.datacamp.com/workspace/w/15d8a8f7-8011-4b68-b06d-35e6f4815972/edit).

**Comment by YunusKaratepe** [comment]
Cosine basis now is a choice with the Legendre. You can switch between them on both command line and UI.
